/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dafny.gradle.plugin;

import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.gradle.api.file.DuplicatesStrategy;
import org.gradle.api.plugins.JavaPlugin;
import org.gradle.api.tasks.TaskProvider;
import org.gradle.language.jvm.tasks.ProcessResources;

/**
 * A simple 'hello world' plugin.
 */
public class DafnyPlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Ensure that the Java plugin is applied.
        project.getPluginManager().apply(JavaPlugin.class);

        TaskProvider<DafnyTranslateTask> dafnyTranslateProvider = project.getTasks()
                .register("dafnyTranslate", DafnyTranslateTask.class);

        dafnyTranslateProvider.configure(dafnyTranslateTask -> {
            dafnyTranslateTask.setClasspath(project.getConfigurations().getByName("compileClasspath"));
        });

        ProcessResources task = project.getTasks().withType(ProcessResources.class).getByName("processResources");
        task.setDuplicatesStrategy(DuplicatesStrategy.EXCLUDE);
        task.dependsOn(dafnyTranslateProvider);
    }
}
