/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dafny.gradle.plugin;

import org.gradle.api.Project;
import org.gradle.api.Plugin;

import java.io.ByteArrayOutputStream;
import java.io.IOException;

/**
 * A simple 'hello world' plugin.
 */
public class DafnyPlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a task
        project.getTasks().register("verify", task -> {
            task.doLast(s -> verify());
        });
    }

    private void verify() {
        Runtime rt = Runtime.getRuntime();
        try {
            Process pr = rt.exec("dafny --version");
            int result = pr.waitFor();
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            byte[] buffer = new byte[4096];
            int read;
            while (0 < (read = pr.getInputStream().read(buffer))) {
                baos.write(buffer, 0, read);
            }
            System.out.println("Dafny version: " + baos.toString());
        } catch (IOException e) {
            throw new RuntimeException(e);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
    }
}
