/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dafny.gradle.plugin;

import java.io.File;
import java.io.IOException;
import java.io.Writer;
import java.io.FileWriter;

import org.gradle.api.GradleException;
import org.gradle.testkit.runner.GradleRunner;
import org.gradle.testkit.runner.BuildResult;
import org.gradle.testkit.runner.UnexpectedBuildFailure;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import static org.junit.jupiter.api.Assertions.*;

/**
 * A simple functional test for the 'dafny.gradle.plugin.greeting' plugin.
 */
class DafnyPluginFunctionalTest {
    @TempDir
    File projectDir;

    @Test void canVerify() throws IOException {
        // Run the build
        BuildResult result = GradleRunner.create()
            .forwardOutput()
            .withPluginClasspath()
            .withArguments("build")
            .withProjectDir(new File("../examples/simple-verify"))
            .buildAndFail();

        Assertions.assertTrue(result.getOutput().contains(
                "examples/simple-verify/src/main/dafny/simple.dfy(2,15): Error: assertion might not hold"));
        Assertions.assertTrue(result.getOutput().contains(
                "examples/simple-verify/src/main/dafny/nested/simple.dfy(2,15): Error: assertion might not hold"));
    }

    @Test void canReferenceDependencies() throws IOException {
        // Run the build
        GradleRunner runner = GradleRunner.create();
        runner.forwardOutput();
        runner.withPluginClasspath();
        runner.withArguments("clean", "build");
        runner.withProjectDir(new File("../examples/multi-project"));
        BuildResult result = runner.build();
    }

    // Expected to fail because the producer and consumer use different values of --unicode-char
    @Test void failsOnIncompatibleDependencies() throws IOException {
        // Run the build
        GradleRunner runner = GradleRunner.create();
        runner.forwardOutput();
        runner.withPluginClasspath();
        runner.withArguments("clean", "build");
        runner.withProjectDir(new File("../examples/multi-project-incompatible"));
        assertThrows(UnexpectedBuildFailure.class, runner::build);
    }

    @Test void succeedsWithNoDafnySourceFiles() throws IOException {
        // Run the build
        GradleRunner runner = GradleRunner.create();
        runner.forwardOutput();
        runner.withPluginClasspath();
        runner.withArguments("clean", "build");
        runner.withProjectDir(new File("../examples/no-dafny"));
        BuildResult result = runner.build();
    }
}
