name: Java CI with Gradle

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Set up Dafny
        uses: dafny-lang/setup-dafny-action@v1.8.0
        with:
          dafny-version: '4.9.1'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --info --stacktrace
