name: Java CI with Gradle

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
      - name: Set up Dafny
        uses: dafny-lang/setup-dafny-action@v1.6.1
        with:
          dafny-version: "nightly-2023-04-29-f006598"
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
